# Generated by Django 3.1.1 on 2020-09-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cname', models.CharField(max_length=15)),
                ('bname', models.CharField(max_length=15)),
                ('phone', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('pan', models.CharField(max_length=15, unique=True)),
                ('adhar', models.IntegerField(unique=True)),
            ],
        ),
    ]
